import { defineConfig } from "oxlint";

const oxlintConfig = defineConfig({
	$schema: "./node_modules/oxlint/configuration_schema.json",
	plugins: ["typescript", "unicorn", "react"],
	categories: {
		correctness: "off",
	},
	env: {
		builtin: true,
		es2026: true,
	},
	ignorePatterns: [
		"**/routeTree.gen.ts",
		"**/logs",
		"**/*.log",
		"**/npm-debug.log*",
		"**/yarn-debug.log*",
		"**/yarn-error.log*",
		"**/pnpm-debug.log*",
		"**/lerna-debug.log*",
		"**/node_modules",
		"**/dist",
		"**/dist-ssr",
		"**/*.local",
		"!.vscode/extensions.json",
		"**/.idea",
		"**/.DS_Store",
		"**/*.suo",
		"**/*.ntvs*",
		"**/*.njsproj",
		"**/*.sln",
		"**/*.sw?",
		"**/.wrangler",
		"**/.tanstack",
	],
	rules: {
		"constructor-super": "error",
		"for-direction": "error",
		"no-async-promise-executor": "error",
		"no-case-declarations": "error",
		"no-class-assign": "error",
		"no-compare-neg-zero": "error",
		"no-cond-assign": "error",
		"no-const-assign": "error",
		"no-constant-binary-expression": "error",
		"no-constant-condition": "error",
		"no-control-regex": "error",
		"no-debugger": "error",
		"no-delete-var": "error",
		"no-dupe-class-members": "error",
		"no-dupe-else-if": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-empty": "error",
		"no-empty-character-class": "error",
		"no-empty-pattern": "error",
		"no-empty-static-block": "error",
		"no-ex-assign": "error",
		"no-extra-boolean-cast": "error",
		"no-fallthrough": "error",
		"no-func-assign": "error",
		"no-global-assign": "error",
		"no-import-assign": "error",
		"no-invalid-regexp": "error",
		"no-irregular-whitespace": "error",
		"no-loss-of-precision": "error",
		"no-misleading-character-class": "error",
		"no-new-native-nonconstructor": "error",
		"no-nonoctal-decimal-escape": "error",
		"no-obj-calls": "error",
		"no-prototype-builtins": "error",
		"no-redeclare": "error",
		"no-regex-spaces": "error",
		"no-self-assign": "error",
		"no-setter-return": "error",
		"no-shadow-restricted-names": "error",
		"no-sparse-arrays": "error",
		"no-this-before-super": "error",
		"no-unassigned-vars": "error",
		"no-unexpected-multiline": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-unsafe-optional-chaining": "error",
		"no-unused-labels": "error",
		"no-unused-private-class-members": "error",
		"no-unused-vars": "error",
		"no-useless-backreference": "error",
		"no-useless-catch": "error",
		"no-useless-escape": "error",
		"no-with": "error",
		"preserve-caught-error": "error",
		"require-yield": "error",
		"use-isnan": "error",
		"valid-typeof": "error",
		"@typescript-eslint/await-thenable": "error",
		"@typescript-eslint/ban-ts-comment": [
			"error",
			{
				minimumDescriptionLength: 10,
			},
		],
		"no-array-constructor": "error",
		"@typescript-eslint/no-array-delete": "error",
		"@typescript-eslint/no-base-to-string": "error",
		"@typescript-eslint/no-confusing-void-expression": "error",
		"@typescript-eslint/no-deprecated": "error",
		"@typescript-eslint/no-duplicate-enum-values": "error",
		"@typescript-eslint/no-duplicate-type-constituents": "error",
		"@typescript-eslint/no-dynamic-delete": "error",
		"@typescript-eslint/no-empty-object-type": "error",
		"@typescript-eslint/no-explicit-any": "error",
		"@typescript-eslint/no-extra-non-null-assertion": "error",
		"@typescript-eslint/no-extraneous-class": "error",
		"@typescript-eslint/no-floating-promises": "error",
		"@typescript-eslint/no-for-in-array": "error",
		"@typescript-eslint/no-implied-eval": "error",
		"@typescript-eslint/no-invalid-void-type": "error",
		"@typescript-eslint/no-meaningless-void-operator": "error",
		"@typescript-eslint/no-misused-new": "error",
		"@typescript-eslint/no-misused-promises": "error",
		"@typescript-eslint/no-misused-spread": "error",
		"@typescript-eslint/no-mixed-enums": "error",
		"@typescript-eslint/no-namespace": "error",
		"@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
		"@typescript-eslint/no-non-null-asserted-optional-chain": "error",
		"@typescript-eslint/no-non-null-assertion": "error",
		"@typescript-eslint/no-redundant-type-constituents": "error",
		"@typescript-eslint/no-require-imports": "error",
		"@typescript-eslint/no-this-alias": "error",
		"@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
		"@typescript-eslint/no-unnecessary-template-expression": "error",
		"@typescript-eslint/no-unnecessary-type-arguments": "error",
		"@typescript-eslint/no-unnecessary-type-assertion": "error",
		"@typescript-eslint/no-unnecessary-type-constraint": "error",
		"@typescript-eslint/no-unsafe-argument": "error",
		"@typescript-eslint/no-unsafe-assignment": "error",
		"@typescript-eslint/no-unsafe-call": "error",
		"@typescript-eslint/no-unsafe-declaration-merging": "error",
		"@typescript-eslint/no-unsafe-enum-comparison": "error",
		"@typescript-eslint/no-unsafe-function-type": "error",
		"@typescript-eslint/no-unsafe-member-access": "error",
		"@typescript-eslint/no-unsafe-return": "error",
		"@typescript-eslint/no-unsafe-unary-minus": "error",
		"no-unused-expressions": "error",
		"no-useless-constructor": "error",
		"@typescript-eslint/no-wrapper-object-types": "error",
		"@typescript-eslint/only-throw-error": "error",
		"@typescript-eslint/prefer-as-const": "error",
		"@typescript-eslint/prefer-literal-enum-member": "error",
		"@typescript-eslint/prefer-namespace-keyword": "error",
		"@typescript-eslint/prefer-promise-reject-errors": "error",
		"@typescript-eslint/prefer-reduce-type-parameter": "error",
		"@typescript-eslint/prefer-return-this-type": "error",
		"@typescript-eslint/related-getter-setter-pairs": "error",
		"@typescript-eslint/require-await": "error",
		"@typescript-eslint/restrict-plus-operands": [
			"error",
			{
				allowAny: false,
				allowBoolean: false,
				allowNullish: false,
				allowNumberAndString: false,
				allowRegExp: false,
			},
		],
		"@typescript-eslint/restrict-template-expressions": [
			"error",
			{
				allowAny: false,
				allowBoolean: false,
				allowNever: false,
				allowNullish: false,
				allowNumber: false,
				allowRegExp: false,
			},
		],
		"@typescript-eslint/return-await": [
			"error",
			"error-handling-correctness-only",
		],
		"@typescript-eslint/triple-slash-reference": "error",
		"@typescript-eslint/unbound-method": "error",
		"@typescript-eslint/unified-signatures": "error",
		"@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
		"@typescript-eslint/adjacent-overload-signatures": "error",
		"@typescript-eslint/array-type": "error",
		"@typescript-eslint/ban-tslint-comment": "error",
		"@typescript-eslint/class-literal-property-style": "error",
		"@typescript-eslint/consistent-generic-constructors": "error",
		"@typescript-eslint/consistent-indexed-object-style": "error",
		"@typescript-eslint/consistent-type-assertions": "error",
		"@typescript-eslint/consistent-type-definitions": ["error", "type"],
		"@typescript-eslint/no-confusing-non-null-assertion": "error",
		"no-empty-function": "error",
		"@typescript-eslint/no-inferrable-types": "error",
		"@typescript-eslint/non-nullable-type-assertion-style": "error",
		"@typescript-eslint/prefer-for-of": "error",
		"@typescript-eslint/prefer-function-type": "error",
		"@typescript-eslint/prefer-includes": "error",
		"@typescript-eslint/prefer-nullish-coalescing": "error",
		"unicorn/catch-error-name": "error",
		"unicorn/consistent-assert": "error",
		"unicorn/consistent-date-clone": "error",
		"unicorn/consistent-empty-array-spread": "error",
		"unicorn/consistent-existence-index-check": "error",
		"unicorn/consistent-function-scoping": "error",
		"unicorn/empty-brace-spaces": "error",
		"unicorn/error-message": "error",
		"unicorn/escape-case": "error",
		"unicorn/explicit-length-check": "error",
		"unicorn/filename-case": "error",
		"unicorn/new-for-builtins": "error",
		"unicorn/no-abusive-eslint-disable": "error",
		"unicorn/no-accessor-recursion": "error",
		"unicorn/no-anonymous-default-export": "error",
		"unicorn/no-array-callback-reference": "error",
		"unicorn/no-array-for-each": "error",
		"unicorn/no-array-method-this-argument": "error",
		"unicorn/no-array-reduce": "error",
		"unicorn/no-array-reverse": "error",
		"unicorn/no-array-sort": "error",
		"unicorn/no-await-expression-member": "error",
		"unicorn/no-await-in-promise-methods": "error",
		"unicorn/no-console-spaces": "error",
		"unicorn/no-document-cookie": "error",
		"unicorn/no-empty-file": "error",
		"unicorn/no-hex-escape": "error",
		"unicorn/no-immediate-mutation": "error",
		"unicorn/no-instanceof-builtins": "error",
		"unicorn/no-invalid-fetch-options": "error",
		"unicorn/no-invalid-remove-event-listener": "error",
		"unicorn/no-lonely-if": "error",
		"unicorn/no-magic-array-flat-depth": "error",
		"unicorn/no-negated-condition": "error",
		"unicorn/no-negation-in-equality-check": "error",
		"unicorn/no-nested-ternary": "error",
		"unicorn/no-new-array": "error",
		"unicorn/no-new-buffer": "error",
		"unicorn/no-null": "error",
		"unicorn/no-object-as-default-parameter": "error",
		"unicorn/no-process-exit": "error",
		"unicorn/no-single-promise-in-promise-methods": "error",
		"unicorn/no-static-only-class": "error",
		"unicorn/no-thenable": "error",
		"unicorn/no-this-assignment": "error",
		"unicorn/no-typeof-undefined": "error",
		"unicorn/no-unnecessary-array-flat-depth": "error",
		"unicorn/no-unnecessary-array-splice-count": "error",
		"unicorn/no-unnecessary-await": "error",
		"unicorn/no-unnecessary-slice-end": "error",
		"unicorn/no-unreadable-array-destructuring": "error",
		"unicorn/no-unreadable-iife": "error",
		"unicorn/no-useless-collection-argument": "error",
		"unicorn/no-useless-error-capture-stack-trace": "error",
		"unicorn/no-useless-fallback-in-spread": "error",
		"unicorn/no-useless-length-check": "error",
		"unicorn/no-useless-promise-resolve-reject": "error",
		"unicorn/no-useless-spread": "error",
		"unicorn/no-useless-switch-case": "error",
		"unicorn/no-useless-undefined": "error",
		"unicorn/no-zero-fractions": "error",
		"unicorn/number-literal-case": "error",
		"unicorn/numeric-separators-style": "error",
		"unicorn/prefer-add-event-listener": "error",
		"unicorn/prefer-array-find": "error",
		"unicorn/prefer-array-flat": "error",
		"unicorn/prefer-array-flat-map": "error",
		"unicorn/prefer-array-index-of": "error",
		"unicorn/prefer-array-some": "error",
		"unicorn/prefer-at": "error",
		"unicorn/prefer-bigint-literals": "error",
		"unicorn/prefer-blob-reading-methods": "error",
		"unicorn/prefer-class-fields": "error",
		"unicorn/prefer-classlist-toggle": "error",
		"unicorn/prefer-code-point": "error",
		"unicorn/prefer-date-now": "error",
		"unicorn/prefer-default-parameters": "error",
		"unicorn/prefer-dom-node-append": "error",
		"unicorn/prefer-dom-node-dataset": "error",
		"unicorn/prefer-dom-node-remove": "error",
		"unicorn/prefer-dom-node-text-content": "error",
		"unicorn/prefer-event-target": "error",
		"unicorn/prefer-global-this": "error",
		"unicorn/prefer-includes": "error",
		"unicorn/prefer-keyboard-event-key": "error",
		"unicorn/prefer-logical-operator-over-ternary": "error",
		"unicorn/prefer-math-min-max": "error",
		"unicorn/prefer-math-trunc": "error",
		"unicorn/prefer-modern-dom-apis": "error",
		"unicorn/prefer-modern-math-apis": "error",
		"unicorn/prefer-module": "error",
		"unicorn/prefer-native-coercion-functions": "error",
		"unicorn/prefer-negative-index": "error",
		"unicorn/prefer-node-protocol": "error",
		"unicorn/prefer-number-properties": "error",
		"unicorn/prefer-object-from-entries": "error",
		"unicorn/prefer-optional-catch-binding": "error",
		"unicorn/prefer-prototype-methods": "error",
		"unicorn/prefer-query-selector": "error",
		"unicorn/prefer-reflect-apply": "error",
		"unicorn/prefer-regexp-test": "error",
		"unicorn/prefer-response-static-json": "error",
		"unicorn/prefer-set-has": "error",
		"unicorn/prefer-set-size": "error",
		"unicorn/prefer-spread": "error",
		"unicorn/prefer-string-raw": "error",
		"unicorn/prefer-string-replace-all": "error",
		"unicorn/prefer-string-slice": "error",
		"unicorn/prefer-string-starts-ends-with": "error",
		"unicorn/prefer-string-trim-start-end": "error",
		"unicorn/prefer-structured-clone": "error",
		"unicorn/prefer-ternary": "error",
		"unicorn/prefer-top-level-await": "error",
		"unicorn/prefer-type-error": "error",
		"unicorn/relative-url-style": "error",
		"unicorn/require-array-join-separator": "error",
		"unicorn/require-module-attributes": "error",
		"unicorn/require-module-specifiers": "error",
		"unicorn/require-number-to-fixed-digits-argument": "error",
		"unicorn/switch-case-braces": "error",
		"unicorn/text-encoding-identifier-case": [
			"error",
			{
				withDash: true,
			},
		],
		"unicorn/throw-new-error": "error",
		"react-hooks/rules-of-hooks": "error",
		"react-hooks/exhaustive-deps": "warn",
		// "@eslint-react/jsx-key-before-spread": "warn",
		// "@eslint-react/jsx-no-comment-textnodes": "warn",
		// "@eslint-react/no-access-state-in-setstate": "error",
		// "@eslint-react/no-array-index-key": "warn",
		// "@eslint-react/no-children-count": "warn",
		// "@eslint-react/no-children-for-each": "warn",
		// "@eslint-react/no-children-map": "warn",
		// "@eslint-react/no-children-only": "warn",
		// "@eslint-react/no-children-to-array": "warn",
		// "@eslint-react/no-clone-element": "warn",
		// "@eslint-react/no-component-will-mount": "error",
		// "@eslint-react/no-component-will-receive-props": "error",
		// "@eslint-react/no-component-will-update": "error",
		// "@eslint-react/no-context-provider": "warn",
		// "@eslint-react/no-create-ref": "error",
		// "@eslint-react/no-default-props": "error",
		// "@eslint-react/no-direct-mutation-state": "error",
		// "@eslint-react/no-forward-ref": "warn",
		// "@eslint-react/no-missing-key": "error",
		// "@eslint-react/no-nested-component-definitions": "error",
		// "@eslint-react/no-nested-lazy-component-declarations": "error",
		// "@eslint-react/no-prop-types": "error",
		// "@eslint-react/no-redundant-should-component-update": "error",
		// "@eslint-react/no-set-state-in-component-did-mount": "warn",
		// "@eslint-react/no-set-state-in-component-did-update": "warn",
		// "@eslint-react/no-set-state-in-component-will-update": "warn",
		// "@eslint-react/no-string-refs": "error",
		// "@eslint-react/no-unnecessary-use-prefix": "warn",
		// "@eslint-react/no-unsafe-component-will-mount": "warn",
		// "@eslint-react/no-unsafe-component-will-receive-props": "warn",
		// "@eslint-react/no-unsafe-component-will-update": "warn",
		// "@eslint-react/no-unused-class-component-members": "warn",
		// "@eslint-react/no-use-context": "warn",
		// "@eslint-react/no-useless-forward-ref": "warn",
		// "@eslint-react/prefer-use-state-lazy-initialization": "warn",
		// "@eslint-react/rsc/function-definition": "error",
		// "@eslint-react/dom/no-dangerously-set-innerhtml": "warn",
		// "@eslint-react/dom/no-dangerously-set-innerhtml-with-children": "error",
		// "@eslint-react/dom/no-find-dom-node": "error",
		// "@eslint-react/dom/no-flush-sync": "error",
		// "@eslint-react/dom/no-hydrate": "error",
		// "@eslint-react/dom/no-namespace": "error",
		// "@eslint-react/dom/no-render": "error",
		// "@eslint-react/dom/no-render-return-value": "error",
		// "@eslint-react/dom/no-script-url": "warn",
		// "@eslint-react/dom/no-unsafe-iframe-sandbox": "warn",
		// "@eslint-react/dom/no-use-form-state": "error",
		// "@eslint-react/dom/no-void-elements-with-children": "error",
		// "@eslint-react/web-api/no-leaked-event-listener": "warn",
		// "@eslint-react/web-api/no-leaked-interval": "warn",
		// "@eslint-react/web-api/no-leaked-resize-observer": "warn",
		// "@eslint-react/web-api/no-leaked-timeout": "warn",
		// "@eslint-react/hooks-extra/no-direct-set-state-in-use-effect": "warn",
		// "@eslint-react/naming-convention/context-name": "warn",
		// "@eslint-react/naming-convention/id-name": "warn",
		// "@eslint-react/naming-convention/ref-name": "warn",
		// "@eslint-react/naming-convention/use-state": "warn",
		// "@eslint-react/jsx-no-iife": "error",
		// "@eslint-react/no-children-prop": "error",
		// "@eslint-react/no-class-component": "error",
		// "@eslint-react/no-misused-capture-owner-stack": "error",
		// "@eslint-react/no-unnecessary-use-callback": "warn",
		// "@eslint-react/no-unnecessary-use-memo": "warn",
		// "@eslint-react/no-unstable-context-value": "warn",
		// "@eslint-react/no-unstable-default-props": "warn",
		// "@eslint-react/no-unused-state": "warn",
		// "@eslint-react/no-useless-fragment": "warn",
		// "@eslint-react/prefer-destructuring-assignment": "warn",
		// "@eslint-react/dom/no-missing-button-type": "warn",
		// "@eslint-react/dom/no-missing-iframe-sandbox": "warn",
		// "@eslint-react/dom/no-unsafe-target-blank": "warn",
		// "@eslint-react/no-implicit-key": "error",
		// "@eslint-react/no-leaked-conditional-rendering": "error",
		// "@eslint-react/no-unused-props": "warn",
		"@tanstack/router/create-route-property-order": "warn",
		"@tanstack/router/route-param-names": "error",
		"simple-import-sort/imports": "warn",
		"simple-import-sort/exports": "warn",
		"@typescript-eslint/no-import-type-side-effects": "error",
		"@typescript-eslint/consistent-type-imports": "error",
		// "@eslint-react/prefer-namespace-import": "error",
		// "@eslint-react/naming-convention/component-name": ["error", "PascalCase"],
		"react-refresh/only-export-components": [
			"error",
			{
				allowConstantExport: true,
				extraHOCs: ["createFileRoute"],
			},
		],
	},
	jsPlugins: [
		// "@eslint-react/eslint-plugin",
		// "@eslint-react/eslint-plugin-rsc",
		// "@eslint-react/eslint-plugin-dom",
		// "@eslint-react/eslint-plugin-web-api",
		// "@eslint-react/eslint-plugin-hooks-extra",
		// "@eslint-react/eslint-plugin-naming-convention",
		"@tanstack/eslint-plugin-router",
		"eslint-plugin-simple-import-sort",
		"eslint-plugin-react-refresh",
	],
	settings: {
		"react-x": {
			version: "detect",
			importSource: "react",
			polymorphicPropName: "as",
		},
	},
	overrides: [
		{
			files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
			rules: {
				"constructor-super": "off",
				"no-class-assign": "off",
				"no-const-assign": "off",
				"no-dupe-class-members": "off",
				"no-dupe-keys": "off",
				"no-func-assign": "off",
				"no-import-assign": "off",
				"no-new-native-nonconstructor": "off",
				"no-obj-calls": "off",
				"no-redeclare": "off",
				"no-setter-return": "off",
				"no-this-before-super": "off",
				"no-unsafe-negation": "off",
				"no-var": "error",
				"no-with": "off",
				"prefer-const": "error",
				"prefer-rest-params": "error",
				"prefer-spread": "error",
			},
		},
	],
});

export default oxlintConfig;
