name = "jasperteo"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-29"

[env.production]
compatibility_date = "2024-04-29"

[env.production.vars]
BUN_VERSION = "1.1.6"
NODE_VERSION = "22.1.0"
